export type MenuCat =
  | "specials"
  | "pizzas"
  | "poutines"
  | "wings"
  | "subs"
  | "burgers"
  | "salads"
  | "sides";

export type MenuItem = {
  id: string;
  cat: MenuCat;
  fr: string;
  en: string;
  toppings: { fr: string; en: string };
  price: string;
  image: string;
  featured?: boolean;
};

export const MENU_CATS: MenuCat[] = [
  "specials",
  "pizzas",
  "poutines",
  "wings",
  "subs",
  "burgers",
  "salads",
  "sides",
];

export const MENU: MenuItem[] = [
  {
    id: "grand-special",
    cat: "specials",
    fr: "Grand Spécial",
    en: "Grand Special",
    toppings: { fr: "2 pizzas — petite, moyenne ou grande", en: "2 pizzas — small, medium or large" },
    price: "dès 40 $",
    image: "/images/pizza-special.jpg",
    featured: true,
  },
  {
    id: "special-italie",
    cat: "specials",
    fr: "Spécial Italie",
    en: "Italie Special",
    toppings: { fr: "Pizza + 10, 15 ou 20 ailes", en: "Pizza + 10, 15 or 20 wings" },
    price: "dès 32 $",
    image: "/images/wings.jpg",
    featured: true,
  },
  {
    id: "combo-italie",
    cat: "specials",
    fr: "Combo Italie",
    en: "Italie Combo",
    toppings: { fr: "Pizza + poutine spéciale", en: "Pizza + special poutine" },
    price: "dès 28 $",
    image: "/images/poutine.jpg",
  },
  {
    id: "maximum-italie",
    cat: "specials",
    fr: "Maximum Italie",
    en: "Maximum Italie",
    toppings: { fr: "Pizza + club poutine", en: "Pizza + club poutine" },
    price: "dès 34 $",
    image: "/images/club-poutine.jpg",
    featured: true,
  },
  {
    id: "nature",
    cat: "pizzas",
    fr: "Nature",
    en: "Plain",
    toppings: { fr: "Sauce, mozzarella", en: "Sauce, mozzarella" },
    price: "dès 16,97 $",
    image: "/images/pizza-plain.jpg",
  },
  {
    id: "pepperoni",
    cat: "pizzas",
    fr: "Pepperoni",
    en: "Pepperoni",
    toppings: { fr: "Pepperoni, mozzarella", en: "Pepperoni, mozzarella" },
    price: "dès 17,97 $",
    image: "/images/pizza-pepperoni.jpg",
  },
  {
    id: "pepperoni-bacon",
    cat: "pizzas",
    fr: "Pepperoni & Vrai Bacon",
    en: "Pepperoni & Real Bacon",
    toppings: { fr: "Pepperoni, vrai bacon", en: "Pepperoni, real bacon" },
    price: "dès 18,97 $",
    image: "/images/pepperoni-bacon.jpg",
    featured: true,
  },
  {
    id: "toute-garnie",
    cat: "pizzas",
    fr: "Toute Garnie Pepperoni",
    en: "All Dressed Pepperoni",
    toppings: { fr: "Pepperoni, poivrons, champignons", en: "Pepperoni, green peppers, mushrooms" },
    price: "dès 19,97 $",
    image: "/images/pizza-deluxe.jpg",
  },
  {
    id: "quebecoise",
    cat: "pizzas",
    fr: "Québécoise",
    en: "Québécoise",
    toppings: { fr: "Pepperoni, bacon, poivrons", en: "Pepperoni, bacon, green peppers" },
    price: "dès 19,97 $",
    image: "/images/pizza-deluxe.jpg",
  },
  {
    id: "deluxe",
    cat: "pizzas",
    fr: "Deluxe",
    en: "Deluxe",
    toppings: { fr: "Toute garnie, bacon, oignons", en: "All dressed, bacon, onions" },
    price: "dès 21,97 $",
    image: "/images/pizza-special.jpg",
  },
  {
    id: "bbq",
    cat: "pizzas",
    fr: "Poulet BBQ",
    en: "BBQ Chicken",
    toppings: { fr: "Sauce BBQ, poulet, tomates, oignons rouges", en: "BBQ sauce, chicken, tomatoes, red onions" },
    price: "dès 20,97 $",
    image: "/images/pizza-bbq.jpg",
  },
  {
    id: "veggie",
    cat: "pizzas",
    fr: "5 Légumes",
    en: "5 Vegetables",
    toppings: { fr: "Olives, poivrons, champignons, tomates, oignons", en: "Green olives, peppers, mushrooms, tomatoes, onions" },
    price: "dès 20,97 $",
    image: "/images/pizza-veggie.jpg",
  },
  {
    id: "hawaiian",
    cat: "pizzas",
    fr: "Hawaïenne & Bacon",
    en: "Hawaiian & Bacon",
    toppings: { fr: "Jambon, ananas, vrai bacon", en: "Ham, pineapple, real bacon" },
    price: "dès 19,97 $",
    image: "/images/pizza-hawaiian.jpg",
  },
  {
    id: "meat",
    cat: "pizzas",
    fr: "Amateur Viande",
    en: "Meat Lover",
    toppings: { fr: "Pepperoni, bacon, jambon, saucisse italienne", en: "Pepperoni, bacon, ham, Italian sausage" },
    price: "dès 22,97 $",
    image: "/images/pizza-meat.jpg",
  },
  {
    id: "mexican",
    cat: "pizzas",
    fr: "Mexicaine",
    en: "Mexican",
    toppings: { fr: "Sauce mexicaine, bœuf, tomate, oignon, olives noires", en: "Mexican sauce, beef, tomato, onion, black olives" },
    price: "dès 20,97 $",
    image: "/images/pizza-mexican.jpg",
  },
  {
    id: "margherita",
    cat: "pizzas",
    fr: "Margherita",
    en: "Margherita",
    toppings: { fr: "Crème à l’ail, tomates, feta, oignons rouges", en: "Garlic cream, tomatoes, feta, red onions" },
    price: "dès 20,97 $",
    image: "/images/pizza-margherita.jpg",
  },
  {
    id: "special-pizza",
    cat: "pizzas",
    fr: "Spécial Italie",
    en: "Special Italie pizza",
    toppings: { fr: "La pizza maison, généreuse", en: "The house pizza, loaded" },
    price: "dès 22,97 $",
    image: "/images/pizza-special.jpg",
  },
  {
    id: "poutine-s",
    cat: "poutines",
    fr: "Poutine petite",
    en: "Small poutine",
    toppings: { fr: "Frites, fromage en grains, sauce", en: "Fries, cheese curds, gravy" },
    price: "dès 8,97 $",
    image: "/images/poutine.jpg",
  },
  {
    id: "poutine-m",
    cat: "poutines",
    fr: "Poutine moyenne",
    en: "Medium poutine",
    toppings: { fr: "Frites, fromage en grains, sauce", en: "Fries, cheese curds, gravy" },
    price: "dès 11,97 $",
    image: "/images/poutine.jpg",
  },
  {
    id: "poutine-l",
    cat: "poutines",
    fr: "Poutine grande",
    en: "Large poutine",
    toppings: { fr: "Frites, fromage en grains, sauce", en: "Fries, cheese curds, gravy" },
    price: "dès 14,97 $",
    image: "/images/poutine.jpg",
    featured: true,
  },
  {
    id: "club-poutine",
    cat: "poutines",
    fr: "Club poutine",
    en: "Club poutine",
    toppings: { fr: "Poulet, bacon, tomates, fromage, sauce", en: "Chicken, bacon, tomatoes, curds, gravy" },
    price: "dès 16,97 $",
    image: "/images/club-poutine.jpg",
  },
  {
    id: "chicken-poutine",
    cat: "poutines",
    fr: "Doigts de poulet poutine",
    en: "Chicken fingers poutine",
    toppings: { fr: "Doigts de poulet, frites, grains, sauce", en: "Chicken fingers, fries, curds, gravy" },
    price: "dès 17,97 $",
    image: "/images/club-poutine.jpg",
  },
  {
    id: "wings",
    cat: "wings",
    fr: "Ailes de poulet",
    en: "Chicken wings",
    toppings: { fr: "10, 15 ou 20 pièces", en: "10, 15 or 20 pieces" },
    price: "dès 14,97 $",
    image: "/images/wings.jpg",
    featured: true,
  },
  {
    id: "wings-special",
    cat: "wings",
    fr: "Spécial Italie ailes",
    en: "Italie wings special",
    toppings: { fr: "Pizza + 10 / 15 / 20 ailes", en: "Pizza + 10 / 15 / 20 wings" },
    price: "dès 32 $",
    image: "/images/wings.jpg",
  },
  {
    id: "philly",
    cat: "subs",
    fr: "Philly Cheese Steak",
    en: "Philly Cheese Steak",
    toppings: { fr: "12 po · bœuf, fromage, poivrons", en: '12" · steak, cheese, peppers' },
    price: "dès 13,97 $",
    image: "/images/sub-philly.jpg",
    featured: true,
  },
  {
    id: "philly-pep",
    cat: "subs",
    fr: "Philly + Pepperoni",
    en: "Philly + Pepperoni",
    toppings: { fr: "12 po · philly et pepperoni", en: '12" · philly and pepperoni' },
    price: "dès 14,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "philly-bacon",
    cat: "subs",
    fr: "Philly + Vrai Bacon",
    en: "Philly + Real Bacon",
    toppings: { fr: "12 po · philly et vrai bacon", en: '12" · philly and real bacon' },
    price: "dès 14,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "special-philly",
    cat: "subs",
    fr: "Special Philadelphia",
    en: "Special Philadelphia",
    toppings: { fr: "Pepperoni + vrai bacon", en: "Pepperoni + real bacon" },
    price: "dès 15,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "ham-sub",
    cat: "subs",
    fr: "Jambon",
    en: "Ham",
    toppings: { fr: "12 po · jambon, fromage", en: '12" · ham, cheese' },
    price: "dès 12,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "chicken-sub",
    cat: "subs",
    fr: "Poulet",
    en: "Chicken",
    toppings: { fr: "12 po · poulet grillé", en: '12" · grilled chicken' },
    price: "dès 13,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "gyro-beef",
    cat: "subs",
    fr: "Gyros au bœuf",
    en: "Beef gyro",
    toppings: { fr: "Bœuf, tzatziki, tomates, oignons", en: "Beef, tzatziki, tomatoes, onions" },
    price: "dès 13,97 $",
    image: "/images/gyro.jpg",
  },
  {
    id: "gyro-mix",
    cat: "subs",
    fr: "Gyros mélange",
    en: "Mixed gyro",
    toppings: { fr: "Mélange maison, tzatziki", en: "House mix, tzatziki" },
    price: "dès 13,97 $",
    image: "/images/gyro.jpg",
  },
  {
    id: "gyro-chicken",
    cat: "subs",
    fr: "Gyros poulet",
    en: "Chicken gyro",
    toppings: { fr: "Poulet, tzatziki, tomates, oignons", en: "Chicken, tzatziki, tomatoes, onions" },
    price: "dès 13,97 $",
    image: "/images/gyro.jpg",
  },
  {
    id: "hamburger",
    cat: "burgers",
    fr: "Hamburger",
    en: "Hamburger",
    toppings: { fr: "Steak haché, bun toasté", en: "Beef patty, toasted bun" },
    price: "dès 10,97 $",
    image: "/images/burger.jpg",
  },
  {
    id: "cheeseburger",
    cat: "burgers",
    fr: "Cheeseburger",
    en: "Cheeseburger",
    toppings: { fr: "Fromage fondu", en: "Melted cheese" },
    price: "dès 11,97 $",
    image: "/images/burger.jpg",
  },
  {
    id: "bacon-cheese",
    cat: "burgers",
    fr: "Bacon cheeseburger",
    en: "Bacon cheeseburger",
    toppings: { fr: "Vrai bacon, cheddar", en: "Real bacon, cheddar" },
    price: "dès 13,97 $",
    image: "/images/burger.jpg",
    featured: true,
  },
  {
    id: "chicken-burger",
    cat: "burgers",
    fr: "Chicken burger",
    en: "Chicken burger",
    toppings: { fr: "Poulet croustillant", en: "Crispy chicken" },
    price: "dès 12,97 $",
    image: "/images/burger.jpg",
  },
  {
    id: "hamburger-steak",
    cat: "burgers",
    fr: "Hamburger steak",
    en: "Hamburger steak",
    toppings: { fr: "Assiette, garnitures", en: "Plated, with sides" },
    price: "dès 14,97 $",
    image: "/images/burger.jpg",
  },
  {
    id: "club",
    cat: "burgers",
    fr: "Club sandwich",
    en: "Club sandwich",
    toppings: { fr: "Poulet, bacon, tomate, laitue", en: "Chicken, bacon, tomato, lettuce" },
    price: "dès 13,97 $",
    image: "/images/sub-philly.jpg",
  },
  {
    id: "nachos",
    cat: "burgers",
    fr: "Nachos",
    en: "Nachos",
    toppings: { fr: "Fromage, jalapeños, salsa", en: "Cheese, jalapeños, salsa" },
    price: "dès 12,97 $",
    image: "/images/nachos.jpg",
  },
  {
    id: "caesar",
    cat: "salads",
    fr: "César",
    en: "Caesar",
    toppings: { fr: "Parmesan, croûtons, sauce", en: "Parmesan, croutons, dressing" },
    price: "dès 8,97 $",
    image: "/images/salad.jpg",
  },
  {
    id: "greek",
    cat: "salads",
    fr: "Grecque",
    en: "Greek",
    toppings: { fr: "Feta, olives, tomates", en: "Feta, olives, tomatoes" },
    price: "dès 9,97 $",
    image: "/images/salad.jpg",
  },
  {
    id: "chicken-salad",
    cat: "salads",
    fr: "Salade au poulet",
    en: "Chicken salad",
    toppings: { fr: "Poulet grillé, verts", en: "Grilled chicken, greens" },
    price: "dès 13,97 $",
    image: "/images/salad.jpg",
  },
  {
    id: "fries",
    cat: "sides",
    fr: "Frites",
    en: "Fries",
    toppings: { fr: "Croustillantes, sel de mer", en: "Crispy, sea salt" },
    price: "dès 4,97 $",
    image: "/images/fries.jpg",
  },
  {
    id: "onion-rings",
    cat: "sides",
    fr: "Onion rings",
    en: "Onion rings",
    toppings: { fr: "Panés, dorés", en: "Battered, golden" },
    price: "dès 6,97 $",
    image: "/images/onion-rings.jpg",
  },
  {
    id: "cheese-sticks",
    cat: "sides",
    fr: "Bâtonnets de fromage",
    en: "Cheese sticks",
    toppings: { fr: "Mozzarella panée", en: "Breaded mozzarella" },
    price: "dès 7,97 $",
    image: "/images/cheese-sticks.jpg",
  },
  {
    id: "garlic-bread",
    cat: "sides",
    fr: "Pain à l’ail",
    en: "Garlic bread",
    toppings: { fr: "Beurre à l’ail, herbes", en: "Garlic butter, herbs" },
    price: "dès 5,97 $",
    image: "/images/garlic-bread.jpg",
  },
  {
    id: "zucchini",
    cat: "sides",
    fr: "Zucchini",
    en: "Zucchini",
    toppings: { fr: "Frit, croustillant", en: "Fried, crisp" },
    price: "dès 6,97 $",
    image: "/images/onion-rings.jpg",
  },
];

export const SIGNATURES = [
  {
    id: "pepperoni-bacon",
    cat: "pizzas" as MenuCat,
    fr: "Pepperoni & Vrai Bacon",
    en: "Pepperoni & Real Bacon",
    price: "dès 18,97 $",
    image: "/images/pepperoni-bacon.jpg",
    line: { fr: "La plus commandée. Généreuse, croustillante, vraie.", en: "The most ordered. Generous, crisp, the real thing." },
  },
  {
    id: "poutine-l",
    cat: "poutines" as MenuCat,
    fr: "Poutine",
    en: "Poutine",
    price: "dès 8,97 $",
    image: "/images/poutine.jpg",
    line: { fr: "Grains qui fondent. On attend que vous arriviez.", en: "Curds that melt. We wait until you walk in." },
  },
  {
    id: "wings",
    cat: "wings" as MenuCat,
    fr: "Ailes",
    en: "Wings",
    price: "dès 14,97 $",
    image: "/images/wings.jpg",
    line: { fr: "Croustillantes, sauce qui tient, parfaites à 3 h.", en: "Crisp, sauce that stays put, perfect at 3am." },
  },
];
